#ifndef ERRORSTATES_H_
#define ERRORSTATES_H_

typedef enum {
    ES_OK,
    ES_NOK,
    ES_NULL_POINTER,
    ES_NOT_INITIALIZED,
    ES_OUT_OF_RANGE,
    ES_INVALID_INPUT,
    ES_INVALID_STATE,
    ES_INVALID_OPERATION,
    ES_INVALID_CONFIG,
    ES_NOT_CONNECTED
}ES_t;

#endif
