#ifndef ERRORSTATES_H_
#define ERRORSTATES_H_

typedef enum {
/*0*/  ES_OK,
/*1*/  ES_NOK,
/*2*/  ES_NULL_POINTER,
/*3*/  ES_NOT_INITIALIZED,
/*4*/  ES_OUT_OF_RANGE,
/*5*/  ES_INVALID_INPUT,
/*6*/  ES_INVALID_STATE,
/*7*/  ES_INVALID_OPERATION,
/*8*/  ES_INVALID_CONFIG,
/*9*/  ES_NOT_CONNECTED,
/*10*/ ES_I2C_NOT_INITIALIZED,
/*11*/ ES_I2C_FAILED,
/*12*/ ES_EEPROM_I2C_FAILED,
/*13*/ ES_DIO_NOT_INITIALIZED,
/*14*/ ES_ADC_NOT_INITIALIZED
}ES_t;

#endif
