#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/* * * * * * * * * * * * * * * * * * * *\
 * CONFIGURATION FOR DIO DRIVER.       *
 * SET PIN DIRECTION AND INITIAL VALUE *
 * BY USING THE AVAIBALBLE VALUES.     *
\* * * * * * * * * * * * * * * * * * * */

 
// INPUT or OUPUT can be used for each pin.
#define PORTA0_DIR INPUT
#define PORTA1_DIR INPUT
#define PORTA2_DIR INPUT
#define PORTA3_DIR INPUT
#define PORTA4_DIR INPUT
#define PORTA5_DIR INPUT
#define PORTA6_DIR INPUT
#define PORTA7_DIR INPUT

#define PORTB0_DIR INPUT
#define PORTB1_DIR INPUT
#define PORTB2_DIR INPUT
#define PORTB3_DIR INPUT
#define PORTB4_DIR INPUT
#define PORTB5_DIR INPUT
#define PORTB6_DIR INPUT
#define PORTB7_DIR INPUT

#define PORTC0_DIR INPUT
#define PORTC1_DIR INPUT
#define PORTC2_DIR INPUT
#define PORTC3_DIR INPUT
#define PORTC4_DIR INPUT
#define PORTC5_DIR INPUT
#define PORTC6_DIR INPUT
#define PORTC7_DIR INPUT

#define PORTD0_DIR INPUT
#define PORTD1_DIR INPUT
#define PORTD2_DIR INPUT
#define PORTD3_DIR INPUT
#define PORTD4_DIR INPUT
#define PORTD5_DIR INPUT
#define PORTD6_DIR INPUT
#define PORTD7_DIR INPUT

// LOW, HIGH,FLOAT or PULL_UP can be used for each pin.
#define PORTA0_VAL LOW
#define PORTA1_VAL LOW
#define PORTA2_VAL LOW
#define PORTA3_VAL LOW
#define PORTA4_VAL LOW
#define PORTA5_VAL LOW
#define PORTA6_VAL LOW
#define PORTA7_VAL LOW

#define PORTB0_VAL LOW
#define PORTB1_VAL LOW
#define PORTB2_VAL LOW
#define PORTB3_VAL LOW
#define PORTB4_VAL LOW
#define PORTB5_VAL LOW
#define PORTB6_VAL LOW
#define PORTB7_VAL LOW

#define PORTC0_VAL LOW
#define PORTC1_VAL LOW
#define PORTC2_VAL LOW
#define PORTC3_VAL LOW
#define PORTC4_VAL LOW
#define PORTC5_VAL LOW
#define PORTC6_VAL LOW
#define PORTC7_VAL LOW

#define PORTD0_VAL LOW
#define PORTD1_VAL LOW
#define PORTD2_VAL LOW
#define PORTD3_VAL LOW
#define PORTD4_VAL LOW
#define PORTD5_VAL LOW
#define PORTD6_VAL LOW
#define PORTD7_VAL LOW



#endif /* DIO_CONFIG_H_ */
